name: CI PokeApp

on:
  pull_request:
    branches:
      - deploy

jobs:
  flutter_analyze_and_test:
    name: Run Flutter analyze and Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter for iOS
    needs: [flutter_analyze]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get

      - name: Clear build
        run: flutter clean

      - name: Build iOS - No CodeSign
        run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter for Android
    needs: [flutter_analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get

      - name: Clear build
        run: flutter clean

      - name: Build Android
        run: flutter build apk

      - run: ls build/app/outputs/flutter-apk
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APPID }}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: poke-app-testers
          file: build/app/outputs/flutter-apk/app-release.apk
          

